var b;b||(b=typeof Module !== 'undefined' ? Module : {});var g={},l;for(l in b)b.hasOwnProperty(l)&&(g[l]=b[l]);var m=!1,n=!1,q=!1,r=!1;
if(b.ENVIRONMENT)if("WEB"===b.ENVIRONMENT)m=!0;else if("WORKER"===b.ENVIRONMENT)n=!0;else if("NODE"===b.ENVIRONMENT)q=!0;else if("SHELL"===b.ENVIRONMENT)r=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else m="object"===typeof window,n="function"===typeof importScripts,q="object"===typeof process&&"function"===typeof require&&!m&&!n,r=!m&&!q&&!n;
if(q){b.print||(b.print=console.log);b.printErr||(b.printErr=console.warn);var t,u;b.read=function(a,c){t||(t=require("fs"));u||(u=require("path"));a=u.normalize(a);a=t.readFileSync(a);return c?a:a.toString()};b.readBinary=function(a){a=b.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};b.thisProgram||(b.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",
function(a){if(!(a instanceof v))throw a;});process.on("unhandledRejection",function(){process.exit(1)});b.inspect=function(){return"[Emscripten Module object]"}}else if(r)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?function(a){return read(a)}:function(){throw"no read() available";},b.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},
"undefined"!=typeof scriptArgs?b.arguments=scriptArgs:"undefined"!=typeof arguments&&(b.arguments=arguments),"function"===typeof quit&&(b.quit=function(a){quit(a)});else if(m||n)b.read=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},n&&(b.readBinary=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),b.readAsync=function(a,c,e){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType=
"arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)},"undefined"!=typeof arguments&&(b.arguments=arguments),"undefined"!==typeof console?(b.print||(b.print=function(a){console.log(a)}),b.printErr||(b.printErr=function(a){console.warn(a)})):b.print||(b.print=function(){}),"undefined"===typeof b.setWindowTitle&&(b.setWindowTitle=function(a){document.title=a});else throw Error("Unknown runtime environment. Where are we?");
b.print||(b.print=function(){});b.printErr||(b.printErr=b.print);b.arguments||(b.arguments=[]);b.thisProgram||(b.thisProgram="./this.program");b.quit||(b.quit=function(a,c){throw c;});b.print=b.print;b.printErr=b.printErr;b.preRun=[];b.postRun=[];for(l in g)g.hasOwnProperty(l)&&(b[l]=g[l]);g=void 0;
var y={O:function(a){return tempRet0=a},K:function(){return tempRet0},m:function(){return w},l:function(a){w=a},I:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?y.c:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},H:function(a){return Math.max(y.I(a),y.c)},P:16,Z:function(a,c){"double"===c||"i64"===c?a&7&&(assert(4===(a&7)),a+=4):assert(0===(a&
3));return a},U:function(a,c,e){return e||"i64"!=a&&"double"!=a?a?Math.min(c||(a?y.H(a):0),y.c):Math.min(c,8):8},g:function(a,c,e){return e&&e.length?b["dynCall_"+a].apply(null,[c].concat(e)):b["dynCall_"+a].call(null,c)},a:[],B:function(a){for(var c=0;c<y.a.length;c++)if(!y.a[c])return y.a[c]=a,2*(1+c);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},N:function(a){y.a[(a-2)/2]=null},b:function(a){y.b.i||(y.b.i={});y.b.i[a]||(y.b.i[a]=1,b.printErr(a))},
h:{},W:function(a,c){if(a){assert(c);y.h[c]||(y.h[c]={});var e=y.h[c];e[a]||(e[a]=1===c.length?function(){return y.g(c,a)}:2===c.length?function(d){return y.g(c,a,[d])}:function(){return y.g(c,a,Array.prototype.slice.call(arguments))});return e[a]}},V:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},j:function(a){var c=w;w=w+a|0;w=w+15&-16;return c},v:function(a){var c=z;z=z+a|0;z=z+15&-16;return c},G:function(a){var c=
A[B>>2];a=(c+a+15|0)&-16;A[B>>2]=a;if(a=a>=C)D(),a=!0;return a?(A[B>>2]=c,0):c},s:function(a,c){return Math.ceil(a/(c?c:16))*(c?c:16)},Y:function(a,c,e){return e?+(a>>>0)+4294967296*+(c>>>0):+(a>>>0)+4294967296*+(c|0)},w:1024,c:4,R:0};b.Runtime=y;y.addFunction=y.B;y.removeFunction=y.N;var E=0;function assert(a,c){a||F("Assertion failed: "+c)}
var I={stackSave:function(){y.m()},stackRestore:function(){y.l()},arrayToC:function(a){var c=y.j(a.length);G.set(a,c);return c},stringToC:function(a){var c=0;if(null!==a&&void 0!==a&&0!==a){var e=(a.length<<2)+1;c=y.j(e);var d=c,h=H;if(0<e){e=d+e-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++k)&1023);if(127>=f){if(d>=e)break;h[d++]=f}else{if(2047>=f){if(d+1>=e)break;h[d++]=192|f>>6}else{if(65535>=f){if(d+2>=e)break;h[d++]=224|f>>12}else{if(2097151>=
f){if(d+3>=e)break;h[d++]=240|f>>18}else{if(67108863>=f){if(d+4>=e)break;h[d++]=248|f>>24}else{if(d+5>=e)break;h[d++]=252|f>>30;h[d++]=128|f>>24&63}h[d++]=128|f>>18&63}h[d++]=128|f>>12&63}h[d++]=128|f>>6&63}h[d++]=128|f&63}}h[d]=0}}return c}},aa={string:I.stringToC,array:I.arrayToC};
b.ccall=function(a,c,e,d){var h=b["_"+a];assert(h,"Cannot call unknown function "+a+", make sure it is exported");var k=[];a=0;if(d)for(var f=0;f<d.length;f++){var p=aa[e[f]];p?(0===a&&(a=y.m()),k[f]=p(d[f])):k[f]=d[f]}e=h.apply(null,k);"string"===c&&(e=ba(e));0!==a&&y.l(a);return e};b.ALLOC_NORMAL=0;b.ALLOC_STACK=1;b.ALLOC_STATIC=2;b.ALLOC_DYNAMIC=3;b.ALLOC_NONE=4;b.getMemory=function(a){return J?L?ca(a):y.G(a):y.v(a)};
function ba(a){var c;if(0===c||!a)return"";for(var e=0,d,h=0;;){d=H[a+h>>0];e|=d;if(0==d&&!c)break;h++;if(c&&h==c)break}c||(c=h);d="";if(128>e){for(;0<c;)e=String.fromCharCode.apply(String,H.subarray(a,a+Math.min(c,1024))),d=d?d+e:e,a+=1024,c-=1024;return d}return da(H,a)}var ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function da(a,c){for(var e=c;a[e];)++e;if(16<e-c&&a.subarray&&ea)return ea.decode(a.subarray(c,e));for(e="";;){var d=a[c++];if(!d)return e;if(d&128){var h=a[c++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|h);else{var k=a[c++]&63;if(224==(d&240))d=(d&15)<<12|h<<6|k;else{var f=a[c++]&63;if(240==(d&248))d=(d&7)<<18|h<<12|k<<6|f;else{var p=a[c++]&63;if(248==(d&252))d=(d&3)<<24|h<<18|k<<12|f<<6|p;else{var x=a[c++]&63;d=(d&1)<<30|h<<24|k<<18|f<<12|p<<6|x}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function fa(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}function ha(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(c){a=c}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}b.extraStackTrace&&(a+="\n"+b.extraStackTrace());return fa(a)}var buffer,G,H,M,ia,A,ja,ka,la;
function ma(){b.HEAP8=G=new Int8Array(buffer);b.HEAP16=M=new Int16Array(buffer);b.HEAP32=A=new Int32Array(buffer);b.HEAPU8=H=new Uint8Array(buffer);b.HEAPU16=ia=new Uint16Array(buffer);b.HEAPU32=ja=new Uint32Array(buffer);b.HEAPF32=ka=new Float32Array(buffer);b.HEAPF64=la=new Float64Array(buffer)}var N,z,J,O,w,P,Q,B;N=z=O=w=P=Q=B=0;J=!1;
function D(){F("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+C+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var R=b.TOTAL_STACK||5242880,C=b.TOTAL_MEMORY||33554432;C<R&&b.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+C+"! (TOTAL_STACK="+R+")");
b.buffer?buffer=b.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(b.wasmMemory=new WebAssembly.Memory({initial:C/65536,maximum:C/65536}),buffer=b.wasmMemory.buffer):buffer=new ArrayBuffer(C);ma();A[0]=1668509029;M[1]=25459;if(115!==H[2]||99!==H[3])throw"Runtime error: expected the system to be little-endian!";b.HEAP=void 0;b.buffer=buffer;b.HEAP8=G;b.HEAP16=M;b.HEAP32=A;b.HEAPU8=H;b.HEAPU16=ia;b.HEAPU32=ja;b.HEAPF32=ka;b.HEAPF64=la;
function S(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c();else{var e=c.T;"number"===typeof e?void 0===c.f?b.dynCall_v(e):b.dynCall_vi(e,c.f):e(void 0===c.f?null:c.f)}}}var na=[],oa=[],pa=[],qa=[],ra=[],L=!1;function sa(){var a=b.preRun.shift();na.unshift(a)}assert(Math.imul&&Math.fround&&Math.clz32&&Math.trunc,"this is a legacy browser, build with LEGACY_VM_SUPPORT");var T=0,U=null,V=null;function ta(){T++;b.monitorRunDependencies&&b.monitorRunDependencies(T)}
b.addRunDependency=ta;function ua(){T--;b.monitorRunDependencies&&b.monitorRunDependencies(T);if(0==T&&(null!==U&&(clearInterval(U),U=null),V)){var a=V;V=null;a()}}b.removeRunDependency=ua;b.preloadedImages={};b.preloadedAudios={};
(function(){function a(){try{if(b.wasmBinary)return new Uint8Array(b.wasmBinary);if(b.readBinary)return b.readBinary(d);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(K){F(K)}}function c(){return b.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(c){c(a())}):fetch(d,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+d+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function e(a){function e(a){f=a.exports;if(f.memory){a=f.memory;var c=b.buffer;a.byteLength<c.byteLength&&b.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(a)).set(c);b.buffer=buffer=a;ma()}b.asm=f;b.usingWasm=!0;ua()}function h(a){e(a.instance)}function K(a){c().then(function(a){return WebAssembly.instantiate(a,k)}).then(a).catch(function(a){b.printErr("failed to asynchronously prepare wasm: "+
a);F(a)})}if("object"!==typeof WebAssembly)return b.printErr("no native wasm support detected"),!1;if(!(b.wasmMemory instanceof WebAssembly.Memory))return b.printErr("no native wasm Memory in use"),!1;a.memory=b.wasmMemory;k.global={NaN:NaN,Infinity:Infinity};k["global.Math"]=Math;k.env=a;ta();if(b.instantiateWasm)try{return b.instantiateWasm(k,e)}catch(za){return b.printErr("Module.instantiateWasm callback failed with error: "+za),!1}b.wasmBinary||"function"!==typeof WebAssembly.M||0===d.indexOf("data:")||
"function"!==typeof fetch?K(h):WebAssembly.M(fetch(d,{credentials:"same-origin"}),k).then(h).catch(function(a){b.printErr("wasm streaming compile failed: "+a);b.printErr("falling back to ArrayBuffer instantiation");K(h)});return{}}var d="scrypt-jane.wasm",h="scrypt-jane.temp.asm.js";"function"===typeof b.locateFile&&(b.locateFile("scrypt-jane.wast"),d=b.locateFile(d),h=b.locateFile(h));var k={global:null,env:null,asm2wasm:{"f64-rem":function(a,c){return a%c},"debugger":function(){debugger}},parent:b},
f=null;b.asmPreload=b.asm;var p=b.reallocBuffer;b.reallocBuffer=function(a){if("asmjs"===x)var c=p(a);else a:{var d=b.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=b.buffer.byteLength;if(b.usingWasm)try{c=-1!==b.wasmMemory.grow((a-d)/65536)?b.buffer=b.wasmMemory.buffer:null;break a}catch(Ba){c=null;break a}c=void 0}return c};var x="";b.asm=function(a,c){if(!c.table){a=b.wasmTableSize;void 0===a&&(a=1024);var d=b.wasmMaxTableSize;c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?
void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);b.wasmTable=c.table}c.memoryBase||(c.memoryBase=b.STATIC_BASE);c.tableBase||(c.tableBase=0);(c=e(c))||F("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return c}})();N=y.w;z=N+5152;oa.push();b.STATIC_BASE=N;b.STATIC_BUMP=5152;z+=16;var W=0;
function X(){W+=4;return A[W-4>>2]}var va={};function Y(a,c){W=c;try{var e=X(),d=X(),h=X();a=0;Y.buffer||(Y.A=[null,[],[]],Y.F=function(a,c){var d=Y.A[a];assert(d);0===c||10===c?((1===a?b.print:b.printErr)(da(d,0)),d.length=0):d.push(c)});for(c=0;c<h;c++){for(var k=A[d+8*c>>2],f=A[d+(8*c+4)>>2],p=0;p<f;p++)Y.F(e,H[k+p]);a+=f}return a}catch(x){return"undefined"!==typeof FS&&x instanceof FS.o||F(x),-x.u}}B=y.v(4);O=w=y.s(z);P=O+R;Q=y.s(P);A[B>>2]=Q;J=!0;b.wasmTableSize=6;b.wasmMaxTableSize=6;b.C={};
b.D={abort:F,enlargeMemory:function(){D()},getTotalMemory:function(){return C},abortOnCannotGrowMemory:D,___setErrNo:function(a){b.___errno_location&&(A[b.___errno_location()>>2]=a);return a},___syscall140:function(a,c){W=c;try{var e=va.J();X();var d=X(),h=X(),k=X();FS.X(e,d,k);A[h>>2]=e.position;e.L&&0===d&&0===k&&(e.L=null);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof FS.o||F(f),-f.u}},___syscall146:Y,___syscall6:function(a,c){W=c;try{var e=va.J();FS.close(e);return 0}catch(d){return"undefined"!==
typeof FS&&d instanceof FS.o||F(d),-d.u}},_emscripten_memcpy_big:function(a,c,e){H.set(H.subarray(c,c+e),a);return a},_exit:function(a){b.exit(a)},DYNAMICTOP_PTR:B,STACKTOP:w,STACK_MAX:P};var wa=b.asm(b.C,b.D,buffer);b.asm=wa;b.___errno_location=function(){return b.asm.___errno_location.apply(null,arguments)};b._emscripten_get_global_libc=function(){return b.asm._emscripten_get_global_libc.apply(null,arguments)};var ca=b._malloc=function(){return b.asm._malloc.apply(null,arguments)};
b._scrypt_hex=function(){return b.asm._scrypt_hex.apply(null,arguments)};b.establishStackSpace=function(){return b.asm.establishStackSpace.apply(null,arguments)};b.getTempRet0=function(){return b.asm.getTempRet0.apply(null,arguments)};b.setTempRet0=function(){return b.asm.setTempRet0.apply(null,arguments)};b.setThrew=function(){return b.asm.setThrew.apply(null,arguments)};b.stackAlloc=function(){return b.asm.stackAlloc.apply(null,arguments)};
b.stackRestore=function(){return b.asm.stackRestore.apply(null,arguments)};b.stackSave=function(){return b.asm.stackSave.apply(null,arguments)};b.dynCall_ii=function(){return b.asm.dynCall_ii.apply(null,arguments)};b.dynCall_iiii=function(){return b.asm.dynCall_iiii.apply(null,arguments)};y.j=b.stackAlloc;y.m=b.stackSave;y.l=b.stackRestore;y.S=b.establishStackSpace;y.O=b.setTempRet0;y.K=b.getTempRet0;b.asm=wa;
function v(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}v.prototype=Error();v.prototype.constructor=v;var xa=null;V=function ya(){b.calledRun||Z();b.calledRun||(V=ya)};
function Z(){function a(){if(!b.calledRun&&(b.calledRun=!0,!E)){L||(L=!0,S(oa));S(pa);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var a=b.postRun.shift();ra.unshift(a)}S(ra)}}null===xa&&(xa=Date.now());if(!(0<T)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)sa();S(na);0<T||b.calledRun||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},
1);a()},1)):a())}}b.run=Z;b.exit=function(a,c){if(!c||!b.noExitRuntime||0!==a){if(!b.noExitRuntime&&(E=!0,w=void 0,S(qa),b.onExit))b.onExit(a);q&&process.exit(a);b.quit(a,new v(a))}};var Aa=[];function F(a){if(b.onAbort)b.onAbort(a);void 0!==a?(b.print(a),b.printErr(a),a=JSON.stringify(a)):a="";E=!0;var c="abort("+a+") at "+ha()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";Aa&&Aa.forEach(function(e){c=e(c,a)});throw c;}b.abort=F;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();b.noExitRuntime=!0;Z();
