"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(b){this.toString=function(){return"CORRUPT: "+this.message};this.message=b},invalid:function(b){this.toString=function(){return"INVALID: "+this.message};this.message=b},bug:function(b){this.toString=function(){return"BUG: "+this.message};this.message=b},notReady:function(b){this.toString=function(){return"NOT READY: "+this.message};this.message=b}}};
sjcl.cipher.aes=function(b){this.c[0][0][0]||this.j();var c,d,a,e,f=this.c[0][4],h=this.c[1];c=b.length;var g=1;if(4!==c&&6!==c&&8!==c)throw new sjcl.exception.invalid("invalid aes key size");this.h=[a=b.slice(0),e=[]];for(b=c;b<4*c+28;b++){d=a[b-1];if(0===b%c||8===c&&4===b%c)d=f[d>>>24]<<24^f[d>>16&255]<<16^f[d>>8&255]<<8^f[d&255],0===b%c&&(d=d<<8^d>>>24^g<<24,g=g<<1^283*(g>>7));a[b]=a[b-c]^d}for(c=0;b;c++,b--)d=a[c&3?b:b-4],e[c]=4>=b||4>c?d:h[0][f[d>>>24]]^h[1][f[d>>16&255]]^h[2][f[d>>8&255]]^h[3][f[d&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(b){return w(this,b,0)},decrypt:function(b){return w(this,b,1)},c:[[[],[],[],[],[]],[[],[],[],[],[]]],j:function(){var b=this.c[0],c=this.c[1],d=b[4],a=c[4],e,f,h,g=[],k=[],l,p,m,n;for(e=0;0x100>e;e++)k[(g[e]=e<<1^283*(e>>7))^e]=e;for(f=h=0;!d[f];f^=l||1,h=k[h]||1)for(m=h^h<<1^h<<2^h<<3^h<<4,m=m>>8^m&255^99,d[f]=m,a[m]=f,p=g[e=g[l=g[f]]],n=0x1010101*p^0x10001*e^0x101*l^0x1010100*f,p=0x101*g[m]^0x1010100*m,e=0;4>e;e++)b[e][f]=p=p<<24^p>>>8,c[e][m]=n=n<<24^n>>>8;for(e=
0;5>e;e++)b[e]=b[e].slice(0),c[e]=c[e].slice(0)}};
function w(b,c,d){if(4!==c.length)throw new sjcl.exception.invalid("invalid aes block size");var a=b.h[d],e=c[0]^a[0],f=c[d?3:1]^a[1],h=c[2]^a[2];c=c[d?1:3]^a[3];var g,k,l,p=a.length/4-2,m,n=4,r=[0,0,0,0];g=b.c[d];b=g[0];var q=g[1],t=g[2],u=g[3],v=g[4];for(m=0;m<p;m++)g=b[e>>>24]^q[f>>16&255]^t[h>>8&255]^u[c&255]^a[n],k=b[f>>>24]^q[h>>16&255]^t[c>>8&255]^u[e&255]^a[n+1],l=b[h>>>24]^q[c>>16&255]^t[e>>8&255]^u[f&255]^a[n+2],c=b[c>>>24]^q[e>>16&255]^t[f>>8&255]^u[h&255]^a[n+3],n+=4,e=g,f=k,h=l;for(m=
0;4>m;m++)r[d?3&-m:m]=v[e>>>24]<<24^v[f>>16&255]<<16^v[h>>8&255]<<8^v[c&255]^a[n++],g=e,e=f,f=h,h=c,c=g;return r}
sjcl.bitArray={bitSlice:function(b,c,d){b=sjcl.bitArray.v(b.slice(c/32),32-(c&31)).slice(1);return void 0===d?b:sjcl.bitArray.clamp(b,d-c)},extract:function(b,c,d){var a=Math.floor(-c-d&31);return((c+d-1^c)&-32?b[c/32|0]<<32-a^b[c/32+1|0]>>>a:b[c/32|0]>>>a)&(1<<d)-1},concat:function(b,c){if(0===b.length||0===c.length)return b.concat(c);var d=b[b.length-1],a=sjcl.bitArray.getPartial(d);return 32===a?b.concat(c):sjcl.bitArray.v(c,a,d|0,b.slice(0,b.length-1))},bitLength:function(b){var c=b.length;return 0===
c?0:32*(c-1)+sjcl.bitArray.getPartial(b[c-1])},clamp:function(b,c){if(32*b.length<c)return b;b=b.slice(0,Math.ceil(c/32));var d=b.length;c=c&31;0<d&&c&&(b[d-1]=sjcl.bitArray.partial(c,b[d-1]&2147483648>>c-1,1));return b},partial:function(b,c,d){return 32===b?c:(d?c|0:c<<32-b)+0x10000000000*b},getPartial:function(b){return Math.round(b/0x10000000000)||32},equal:function(b,c){if(sjcl.bitArray.bitLength(b)!==sjcl.bitArray.bitLength(c))return!1;var d=0,a;for(a=0;a<b.length;a++)d|=b[a]^c[a];return 0===
d},v:function(b,c,d,a){var e;e=0;for(void 0===a&&(a=[]);32<=c;c-=32)a.push(d),d=0;if(0===c)return a.concat(b);for(e=0;e<b.length;e++)a.push(d|b[e]>>>c),d=b[e]<<32-c;e=b.length?b[b.length-1]:0;b=sjcl.bitArray.getPartial(e);a.push(sjcl.bitArray.partial(c+b&31,32<c+b?d:a.pop(),1));return a},B:function(b,c){return[b[0]^c[0],b[1]^c[1],b[2]^c[2],b[3]^c[3]]},byteswapM:function(b){var c,d;for(c=0;c<b.length;++c)d=b[c],b[c]=d>>>24|d>>>8&0xff00|(d&0xff00)<<8|d<<24;return b}};
sjcl.codec.utf8String={fromBits:function(b){var c="",d=sjcl.bitArray.bitLength(b),a,e;for(a=0;a<d/8;a++)0===(a&3)&&(e=b[a/4]),c+=String.fromCharCode(e>>>8>>>8>>>8),e<<=8;return decodeURIComponent(escape(c))},toBits:function(b){b=unescape(encodeURIComponent(b));var c=[],d,a=0;for(d=0;d<b.length;d++)a=a<<8|b.charCodeAt(d),3===(d&3)&&(c.push(a),a=0);d&3&&c.push(sjcl.bitArray.partial(8*(d&3),a));return c}};
sjcl.codec.hex={fromBits:function(b){var c="",d;for(d=0;d<b.length;d++)c+=((b[d]|0)+0xf00000000000).toString(16).substr(4);return c.substr(0,sjcl.bitArray.bitLength(b)/4)},toBits:function(b){var c,d=[],a;b=b.replace(/\s|0x/g,"");a=b.length;b=b+"00000000";for(c=0;c<b.length;c+=8)d.push(parseInt(b.substr(c,8),16)^0);return sjcl.bitArray.clamp(d,4*a)}};
sjcl.codec.base64={m:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(b,c,d){var a="",e=0,f=sjcl.codec.base64.m,h=0,g=sjcl.bitArray.bitLength(b);d&&(f=f.substr(0,62)+"-_");for(d=0;6*a.length<g;)a+=f.charAt((h^b[d]>>>e)>>>26),6>e?(h=b[d]<<6-e,e+=26,d++):(h<<=6,e-=6);for(;a.length&3&&!c;)a+="=";return a},toBits:function(b,c){b=b.replace(/\s|=/g,"");var d=[],a,e=0,f=sjcl.codec.base64.m,h=0,g;c&&(f=f.substr(0,62)+"-_");for(a=0;a<b.length;a++){g=f.indexOf(b.charAt(a));
if(0>g)throw new sjcl.exception.invalid("this isn't base64!");26<e?(e-=26,d.push(h^g>>>e),h=g<<32-e):(e+=6,h^=g<<32-e)}e&56&&d.push(sjcl.bitArray.partial(e&56,h,1));return d}};sjcl.codec.base64url={fromBits:function(b){return sjcl.codec.base64.fromBits(b,1,1)},toBits:function(b){return sjcl.codec.base64.toBits(b,1)}};
sjcl.codec.bytes={fromBits:function(b){var c=[],d=sjcl.bitArray.bitLength(b),a,e;for(a=0;a<d/8;a++)0===(a&3)&&(e=b[a/4]),c.push(e>>>24),e<<=8;return c},toBits:function(b){var c=[],d,a=0;for(d=0;d<b.length;d++)a=a<<8|b[d],3===(d&3)&&(c.push(a),a=0);d&3&&c.push(sjcl.bitArray.partial(8*(d&3),a));return c}};sjcl.hash.sha256=function(b){this.h[0]||this.j();b?(this.i=b.i.slice(0),this.g=b.g.slice(0),this.b=b.b):this.reset()};sjcl.hash.sha256.hash=function(b){return(new sjcl.hash.sha256).update(b).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.i=this.u.slice(0);this.g=[];this.b=0;return this},update:function(b){"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));var c,d=this.g=sjcl.bitArray.concat(this.g,b);c=this.b;b=this.b=c+sjcl.bitArray.bitLength(b);if(0x1fffffffffffff<b)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var a=new Uint32Array(d),e=0;for(c=512+c-(512+c&0x1ff);c<=b;c+=512)x(this,a.subarray(16*e,
16*(e+1))),e+=1;d.splice(0,16*e)}else for(c=512+c-(512+c&0x1ff);c<=b;c+=512)x(this,d.splice(0,16));return this},finalize:function(){var b,c=this.g,d=this.i,c=sjcl.bitArray.concat(c,[sjcl.bitArray.partial(1,1)]);for(b=c.length+2;b&15;b++)c.push(0);c.push(Math.floor(this.b/0x100000000));for(c.push(this.b|0);c.length;)x(this,c.splice(0,16));this.reset();return d},u:[],h:[],j:function(){function b(a){return 0x100000000*(a-Math.floor(a))|0}for(var c=0,d=2,a,e;64>c;d++){e=!0;for(a=2;a*a<=d;a++)if(0===d%a){e=
!1;break}e&&(8>c&&(this.u[c]=b(Math.pow(d,.5))),this.h[c]=b(Math.pow(d,1/3)),c++)}}};
function x(b,c){var d,a,e,f=b.i,h=b.h,g=f[0],k=f[1],l=f[2],p=f[3],m=f[4],n=f[5],r=f[6],q=f[7];for(d=0;64>d;d++)16>d?a=c[d]:(a=c[d+1&15],e=c[d+14&15],a=c[d&15]=(a>>>7^a>>>18^a>>>3^a<<25^a<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+c[d&15]+c[d+9&15]|0),a=a+q+(m>>>6^m>>>11^m>>>25^m<<26^m<<21^m<<7)+(r^m&(n^r))+h[d],q=r,r=n,n=m,m=p+a|0,p=l,l=k,k=g,g=a+(k&l^p&(k^l))+(k>>>2^k>>>13^k>>>22^k<<30^k<<19^k<<10)|0;f[0]=f[0]+g|0;f[1]=f[1]+k|0;f[2]=f[2]+l|0;f[3]=f[3]+p|0;f[4]=f[4]+m|0;f[5]=f[5]+n|0;f[6]=f[6]+r|0;f[7]=
f[7]+q|0}
sjcl.mode.gcm={name:"gcm",encrypt:function(b,c,d,a,e){var f=c.slice(0);c=sjcl.bitArray;a=a||[];b=sjcl.mode.gcm.o(!0,b,f,a,d,e||128);return c.concat(b.data,b.tag)},decrypt:function(b,c,d,a,e){var f=c.slice(0),h=sjcl.bitArray,g=h.bitLength(f);e=e||128;a=a||[];e<=g?(c=h.bitSlice(f,g-e),f=h.bitSlice(f,0,g-e)):(c=f,f=[]);b=sjcl.mode.gcm.o(!1,b,f,a,d,e);if(!h.equal(b.tag,c))throw new sjcl.exception.corrupt("gcm: tag doesn't match");return b.data},A:function(b,c){var d,a,e,f,h,g=sjcl.bitArray.B;e=[0,0,0,
0];f=c.slice(0);for(d=0;128>d;d++){(a=0!==(b[Math.floor(d/32)]&1<<31-d%32))&&(e=g(e,f));h=0!==(f[3]&1);for(a=3;0<a;a--)f[a]=f[a]>>>1|(f[a-1]&1)<<31;f[0]>>>=1;h&&(f[0]^=-0x1f000000)}return e},a:function(b,c,d){var a,e=d.length;c=c.slice(0);for(a=0;a<e;a+=4)c[0]^=0xffffffff&d[a],c[1]^=0xffffffff&d[a+1],c[2]^=0xffffffff&d[a+2],c[3]^=0xffffffff&d[a+3],c=sjcl.mode.gcm.A(c,b);return c},o:function(b,c,d,a,e,f){var h,g,k,l,p,m,n,r,q=sjcl.bitArray;m=d.length;n=q.bitLength(d);r=q.bitLength(a);g=q.bitLength(e);
h=c.encrypt([0,0,0,0]);96===g?(e=e.slice(0),e=q.concat(e,[1])):(e=sjcl.mode.gcm.a(h,[0,0,0,0],e),e=sjcl.mode.gcm.a(h,e,[0,0,Math.floor(g/0x100000000),g&0xffffffff]));g=sjcl.mode.gcm.a(h,[0,0,0,0],a);p=e.slice(0);a=g.slice(0);b||(a=sjcl.mode.gcm.a(h,g,d));for(l=0;l<m;l+=4)p[3]++,k=c.encrypt(p),d[l]^=k[0],d[l+1]^=k[1],d[l+2]^=k[2],d[l+3]^=k[3];d=q.clamp(d,n);b&&(a=sjcl.mode.gcm.a(h,g,d));b=[Math.floor(r/0x100000000),r&0xffffffff,Math.floor(n/0x100000000),n&0xffffffff];a=sjcl.mode.gcm.a(h,a,b);k=c.encrypt(e);
a[0]^=k[0];a[1]^=k[1];a[2]^=k[2];a[3]^=k[3];return{tag:q.bitSlice(a,0,f),data:d}}};sjcl.misc.hmac=function(b,c){this.s=c=c||sjcl.hash.sha256;var d=[[],[]],a,e=c.prototype.blockSize/32;this.f=[new c,new c];b.length>e&&(b=c.hash(b));for(a=0;a<e;a++)d[0][a]=b[a]^909522486,d[1][a]=b[a]^1549556828;this.f[0].update(d[0]);this.f[1].update(d[1]);this.l=new c(this.f[0])};
sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(b){if(this.w)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(b);return this.digest(b)};sjcl.misc.hmac.prototype.reset=function(){this.l=new this.s(this.f[0]);this.w=!1};sjcl.misc.hmac.prototype.update=function(b){this.w=!0;this.l.update(b)};sjcl.misc.hmac.prototype.digest=function(){var b=this.l.finalize(),b=(new this.s(this.f[1])).update(b).finalize();this.reset();return b};
sjcl.misc.pbkdf2=function(b,c,d,a,e){d=d||1E4;if(0>a||0>d)throw new sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));"string"===typeof c&&(c=sjcl.codec.utf8String.toBits(c));e=e||sjcl.misc.hmac;b=new e(b);var f,h,g,k,l=[],p=sjcl.bitArray;for(k=1;32*l.length<(a||1);k++){e=f=b.encrypt(p.concat(c,[k]));for(h=1;h<d;h++)for(f=b.encrypt(f),g=0;g<f.length;g++)e[g]^=f[g];l=l.concat(e)}a&&(l=p.clamp(l,a));return l};
sjcl.misc.scrypt=function(b,c,d,a,e,f,h){var g=Math.pow(2,32)-1,k=sjcl.misc.scrypt;d=d||16384;a=a||8;e=e||1;if(a*e>=Math.pow(2,30))throw sjcl.exception.invalid("The parameters r, p must satisfy r * p < 2^30");if(2>d||d&0!=d-1)throw sjcl.exception.invalid("The parameter N must be a power of 2.");if(d>g/128/a)throw sjcl.exception.invalid("N too big.");if(a>g/128/e)throw sjcl.exception.invalid("r too big.");c=sjcl.misc.pbkdf2(b,c,1,128*e*a*8,h);a=c.length/e;k.reverse(c);for(g=0;g<e;g++){var l=c.slice(g*
a,(g+1)*a);k.blockcopy(k.ROMix(l,d),0,c,g*a)}k.reverse(c);return sjcl.misc.pbkdf2(b,c,1,f,h)};
sjcl.misc.scrypt.salsa20Core=function(b,c){function d(a,b){return a<<b|a>>>32-b}for(var a=b.slice(0),e=c;0<e;e-=2)a[4]^=d(a[0]+a[12],7),a[8]^=d(a[4]+a[0],9),a[12]^=d(a[8]+a[4],13),a[0]^=d(a[12]+a[8],18),a[9]^=d(a[5]+a[1],7),a[13]^=d(a[9]+a[5],9),a[1]^=d(a[13]+a[9],13),a[5]^=d(a[1]+a[13],18),a[14]^=d(a[10]+a[6],7),a[2]^=d(a[14]+a[10],9),a[6]^=d(a[2]+a[14],13),a[10]^=d(a[6]+a[2],18),a[3]^=d(a[15]+a[11],7),a[7]^=d(a[3]+a[15],9),a[11]^=d(a[7]+a[3],13),a[15]^=d(a[11]+a[7],18),a[1]^=d(a[0]+a[3],7),a[2]^=
d(a[1]+a[0],9),a[3]^=d(a[2]+a[1],13),a[0]^=d(a[3]+a[2],18),a[6]^=d(a[5]+a[4],7),a[7]^=d(a[6]+a[5],9),a[4]^=d(a[7]+a[6],13),a[5]^=d(a[4]+a[7],18),a[11]^=d(a[10]+a[9],7),a[8]^=d(a[11]+a[10],9),a[9]^=d(a[8]+a[11],13),a[10]^=d(a[9]+a[8],18),a[12]^=d(a[15]+a[14],7),a[13]^=d(a[12]+a[15],9),a[14]^=d(a[13]+a[12],13),a[15]^=d(a[14]+a[13],18);for(e=0;16>e;e++)b[e]=a[e]+b[e]};
sjcl.misc.scrypt.blockMix=function(b){for(var c=b.slice(-16),d=[],a=b.length/16,e=sjcl.misc.scrypt,f=0;f<a;f++)e.blockxor(b,16*f,c,0,16),e.salsa20Core(c,8),0==(f&1)?e.blockcopy(c,0,d,8*f):e.blockcopy(c,0,d,8*(f^1+a));return d};sjcl.misc.scrypt.ROMix=function(b,c){for(var d=b.slice(0),a=[],e=sjcl.misc.scrypt,f=0;f<c;f++)a.push(d.slice(0)),d=e.blockMix(d);for(f=0;f<c;f++)e.blockxor(a[d[d.length-16]&c-1],0,d,0),d=e.blockMix(d);return d};
sjcl.misc.scrypt.reverse=function(b){for(var c in b){var d=b[c]&255,d=d<<8|b[c]>>>8&255,d=d<<8|b[c]>>>16&255,d=d<<8|b[c]>>>24&255;b[c]=d}};sjcl.misc.scrypt.blockcopy=function(b,c,d,a,e){var f;e=e||b.length-c;for(f=0;f<e;f++)d[a+f]=b[c+f]|0};sjcl.misc.scrypt.blockxor=function(b,c,d,a,e){var f;e=e||b.length-c;for(f=0;f<e;f++)d[a+f]=d[a+f]^b[c+f]|0};"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
